# Generated by Django 5.0 on 2023-12-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(default='', upload_to='receipe'),
        ),
    ]
